"""
status.py - Status composition for global and per-room status entities

Responsibilities:
- Compose sensor.pyheat_status state and attributes from module snapshots
- Generate per-room status strings (sensor.pyheat_<room>_status)
- Keep all status formatting and reason strings in one place
- No HA I/O - returns payloads that core.py publishes

Status States (sensor.pyheat_status):
- "heating (N rooms)" - At least one room calling for heat
- "idle" - No rooms calling for heat
- "disabled" - Master enable off
- "holiday" - Holiday mode active
- "error" - System error or all rooms stale

Per-room Status Strings (sensor.pyheat_<room>_status):
- "off" - Room mode is off
- "stale" - All sensors unavailable
- "manual(T°C)" - Manual mode with setpoint
- "manual(stale)" - Manual mode but sensors stale
- "at_target" - Room at target temperature
- "heating" - Room calling for heat
- "override(T°C) Nm" - Absolute override with time remaining
- "boost(±D°C) Nm" - Delta boost with time remaining
"""

from typing import Dict, List, Optional, Any, Tuple


def short_reason_for_room(room: Dict[str, Any]) -> str:
    """Produce per-room status reason string.
    
    Incorporates mode, user_setpoint when manual, and handles
    stale/override/boost cases.
    
    Args:
        room: Room status dict with keys:
            - state: "auto" | "manual" | "off" | "stale"
            - mode: same as state (for compatibility)
            - temp: float | None
            - target: float | None
            - call_for_heat: bool
            - manual_setpoint: float | None (only when mode=manual)
            - override_active: bool
            - override_remaining_m: int | None
            - status: str (generated by room_controller)
            
    Returns:
        Short status string like:
        - "off"
        - "stale"
        - "manual(20.0°C)"
        - "manual(stale)"
        - "at_target"
        - "heating"
        - "override(21.0°C) 15m"
        - "boost(+2.0°C) 23m"
    """
    # Use the status string generated by room_controller if available
    # It already handles all the cases we need
    if "status" in room and room["status"]:
        return room["status"]
    
    # Fallback for compatibility if status not provided
    state = room.get("state", room.get("mode", "auto"))
    
    if state == "off":
        return "off"
    
    if state == "stale":
        return "stale"
    
    if state == "manual":
        manual_setpoint = room.get("manual_setpoint")
        is_stale = room.get("is_stale", True)
        
        if is_stale:
            return "manual(stale)"
        elif manual_setpoint is not None:
            return f"manual({manual_setpoint:.1f}°C)"
        else:
            return "manual(no setpoint)"
    
    # Auto mode
    call_for_heat = room.get("call_for_heat", False)
    
    if call_for_heat:
        return "heating"
    else:
        return "at_target"


def build_status(
    *,
    master_enable: bool,
    holiday: bool,
    rooms: List[Dict[str, Any]],
    boiler: Optional[Dict[str, Any]] = None
) -> Tuple[str, Dict[str, Any]]:
    """Build global status entity state and attributes.
    
    Args:
        master_enable: True if pyheat is enabled
        holiday: True if holiday mode active
        rooms: List of room status dicts (from room_controller.compute())
        boiler: Optional boiler status dict
        
    Returns:
        Tuple of (state_str, attributes_dict) for sensor.pyheat_status
        
    Example:
        >>> build_status(master_enable=True, holiday=False, rooms=[...])
        ("heating (2 rooms)", {
            "mode": "enabled",
            "any_call_for_heat": True,
            "active_rooms": ["lounge", "pete"],
            "room_calling_count": 2,
            "rooms": [...]
        })
    """
    # Determine mode
    if not master_enable:
        mode = "disabled"
    elif holiday:
        mode = "holiday"
    else:
        mode = "enabled"
    
    # Filter rooms calling for heat (avoid list comprehension for pyscript)
    calling_rooms = []
    for r in rooms:
        if r.get("call_for_heat", False) and r.get("state") not in ["off", "stale"]:
            calling_rooms.append(r)
    
    # Get active room IDs (avoid list comprehension)
    active_room_ids = []
    for r in calling_rooms:
        active_room_ids.append(r.get("room_id"))
    
    room_calling_count = len(calling_rooms)
    any_call_for_heat = room_calling_count > 0
    
    # Determine state string (avoid all() generator expression)
    all_stale = True
    for r in rooms:
        if r.get("state") != "stale":
            all_stale = False
            break
    
    if not master_enable:
        state_str = "disabled"
    elif all_stale and len(rooms) > 0:
        # All rooms stale
        state_str = "error (all stale)"
    elif any_call_for_heat:
        # At least one room calling
        suffix = 's' if room_calling_count != 1 else ''
        state_str = "heating (" + str(room_calling_count) + " room" + suffix + ")"
    else:
        # Idle
        state_str = "idle"
    
    # Build attributes
    attributes = {
        "mode": mode,
        "any_call_for_heat": any_call_for_heat,
        "active_rooms": active_room_ids,
        "room_calling_count": room_calling_count,
        "rooms": _format_rooms_for_attributes(rooms),
    }
    
    # Add boiler info if available
    if boiler:
        # New state machine structure
        boiler_state = boiler.get("state", "unknown")
        boiler_on = boiler.get("on", False)
        
        attributes["boiler"] = {
            "state": boiler_state,
            "is_on": boiler_on,
            "hvac_action": boiler.get("hvac_action", "unknown"),
            "reason": boiler.get("reason", ""),
            "interlock_ok": boiler.get("interlock_ok", True),
            "total_valve_percent": boiler.get("total_valve_percent", 0),
            "rooms_calling": boiler.get("rooms_calling", 0),
            "time_in_state_s": int(boiler.get("time_in_state_s", 0)),
        }
    
    return state_str, attributes


def _format_rooms_for_attributes(rooms: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Format room data for status attributes.
    
    Includes: id, mode, temp, target, user_setpoint (when manual), reason
    
    Args:
        rooms: List of room status dicts
        
    Returns:
        List of formatted room dicts for attributes
    """
    formatted = []
    
    for room in rooms:
        room_id = room.get("room_id", "unknown")
        state = room.get("state", "auto")
        temp = room.get("temp")
        target = room.get("target")
        manual_setpoint = room.get("manual_setpoint")
        call_for_heat = room.get("call_for_heat", False)
        
        # Generate reason string
        reason = short_reason_for_room(room)
        
        # Build formatted dict
        formatted_room = {
            "id": room_id,
            "mode": state,
            "temp": round(temp, 1) if temp is not None else None,
            "target": round(target, 1) if target is not None else None,
            "call_for_heat": call_for_heat,
            "reason": reason,
        }
        
        # Include user_setpoint only when mode is manual
        if state == "manual" and manual_setpoint is not None:
            formatted_room["user_setpoint"] = round(manual_setpoint, 1)
        
        formatted.append(formatted_room)
    
    return formatted


def build_room_status(room: Dict[str, Any]) -> Tuple[str, Dict[str, Any]]:
    """Build per-room status entity state and attributes.
    
    Args:
        room: Room status dict from room_controller.compute()
        
    Returns:
        Tuple of (state_str, attributes_dict) for sensor.pyheat_<room>_status
        
    Example:
        >>> build_room_status({"room_id": "pete", "state": "auto", ...})
        ("heating", {
            "room_id": "pete",
            "mode": "auto",
            "temp": 19.2,
            "target": 20.0,
            "call_for_heat": True,
            "valve_percent": 65,
            ...
        })
    """
    # State is the short reason string
    state_str = short_reason_for_room(room)
    
    # Attributes include full room status
    attributes = {
        "room_id": room.get("room_id"),
        "mode": room.get("state"),
        "temp": room.get("temp"),
        "target": room.get("target"),
        "call_for_heat": room.get("call_for_heat", False),
        "valve_percent": room.get("valve_percent", 0),
        "override_active": room.get("override_active", False),
        "override_remaining_m": room.get("override_remaining_m"),
    }
    
    # Add manual setpoint if in manual mode
    if room.get("state") == "manual" and room.get("manual_setpoint") is not None:
        attributes["manual_setpoint"] = room.get("manual_setpoint")
    
    return state_str, attributes


def format_temp(temp: Optional[float], precision: int = 1) -> str:
    """Format temperature for display.
    
    Args:
        temp: Temperature in °C or None
        precision: Decimal places
        
    Returns:
        Formatted string like "19.5°C" or "N/A"
    """
    if temp is None:
        return "N/A"
    return f"{temp:.{precision}f}°C"


def format_duration(minutes: Optional[int]) -> str:
    """Format duration in minutes.
    
    Args:
        minutes: Duration in minutes or None
        
    Returns:
        Formatted string like "23m", "1h 15m", or "N/A"
    """
    if minutes is None or minutes < 0:
        return "N/A"
    
    if minutes < 60:
        return f"{minutes}m"
    
    hours = minutes // 60
    mins = minutes % 60
    
    if mins == 0:
        return f"{hours}h"
    
    return f"{hours}h {mins}m"


# No singleton needed - this module is stateless and just provides utility functions

