rooms:
- id: pete
  default_target: 10.0
  week:
    mon:
    - start: '06:00'
      end: '07:15'
      target: 18.0
    - start: '09:15'
      end: '12:15'
      target: 24.0
    - start: '16:00'
      end: '19:00'
      target: 17.5
    - start: '19:00'
      end: '21:00'
      target: 21.0
    tue:
    - start: '06:00'
      end: '07:15'
      target: 18.0
    - start: '16:00'
      end: '19:00'
      target: 17.5
    - start: '19:00'
      end: '21:00'
      target: 21.0
    wed:
    - start: '06:00'
      end: '07:15'
      target: 18.0
    - start: '16:00'
      end: '19:00'
      target: 17.5
    - start: '19:00'
      end: '21:00'
      target: 21.0
    thu:
    - start: '06:00'
      end: '07:15'
      target: 18.0
    - start: '16:00'
      end: '19:00'
      target: 17.5
    - start: '19:00'
      end: '21:00'
      target: 21.0
    fri:
    - start: '06:00'
      end: '07:15'
      target: 18.0
    - start: '16:00'
      end: '19:00'
      target: 17.5
    - start: '19:00'
      end: '21:00'
      target: 21.0
    sat:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    - start: '11:00'
      end: '13:00'
      target: 21.0
    - start: '13:00'
      end: '15:00'
      target: 21.0
    sun: []
- id: lounge
  default_target: 10.0
  week:
    mon:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    - start: '11:00'
      end: '14:00'
      target: 21.0
    tue:
    - start: '07:00'
      end: '10:00'
      target: 21.0
    wed:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    thu:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    fri:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    sat: []
    sun: []
- id: games
  default_target: 10.0
  week:
    mon:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    - start: '11:00'
      end: '14:00'
      target: 21.0
    tue:
    - start: '07:00'
      end: '10:00'
      target: 21.0
    wed:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    thu:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    fri:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    sat: []
    sun: []
- id: abby
  default_target: 10.0
  week:
    mon:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    - start: '11:00'
      end: '14:00'
      target: 21.0
    tue:
    - start: '07:00'
      end: '10:00'
      target: 21.0
    wed:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    thu:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    fri:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    sat: []
    sun: []
- id: office
  default_target: 10.0
  week:
    mon:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    - start: '11:00'
      end: '14:00'
      target: 21.0
    tue:
    - start: '07:00'
      end: '10:00'
      target: 21.0
    wed:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    thu:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    fri:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    sat: []
    sun: []
- id: bathroom
  default_target: 10.0
  week:
    mon:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    - start: '11:00'
      end: '14:00'
      target: 21.0
    tue:
    - start: '07:00'
      end: '10:00'
      target: 21.0
    wed:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    thu:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    fri:
    - start: '07:00'
      end: '09:00'
      target: 21.0
    sat: []
    sun: []
