rooms:
- default_target: 19.5
  id: pete
  week:
    fri:
    - end: 09:00
      start: 07:00
      target: 21.0
    mon:
    - end: 09:00
      start: 07:00
      target: 21.0
    sat: []
    sun: []
    thu:
    - end: 09:00
      start: 07:00
      target: 21.0
    tue:
    - end: 09:00
      start: 07:00
      target: 21.0
    wed:
    - end: 09:00
      start: 07:00
      target: 21.0
